apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-pedidos-hpa
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-pedidos
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource