version: "3.8"
services:
  mysqldb:
    container_name: mysqldb_pedidos
    image: mysql:8.0
    restart: always
    networks:
      - pedidos-net
    environment:
      MYSQL_DATABASE: food_58
      MYSQL_ROOT_PASSWORD: /run/secrets/db_pass
    secrets:
      - db_pass

  pedidos_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - pedidos-net
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: /run/secrets/db_pass
      MYSQL_DB: food_58
    secrets:
      - db_pass
    working_dir: /usr/src/pedidos
    command: /usr/src/pedidos/app-startup.sh

networks:
  pedidos-net:
    driver: bridge

secrets:
  db_pass:
    file: db_pass.txt