-- Script para gerar tabelas

CREATE TABLE Clientes (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CRIADO_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,
    DELETADO_EM TIMESTAMP
);

CREATE TABLE Enderecos (
    ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    RUA VARCHAR(200) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,
    COMPLEMENTO VARCHAR(20) NOT NULL,
    CRIADO_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,
    DELETADO_EM TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE)
);

CREATE TABLE Telefones (
    ID_TELEFONE INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    DDD VARCHAR(2) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    TIPO VARCHAR(20),
    CRIADO_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,
    DELETADO_EM TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE)
);

CREATE TABLE Categorias (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(50) NOT NULL,
    CRIADO_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,
    DELETADO_EM TIMESTAMP);

CREATE TABLE Produtos (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    FOTO BLOB,
    PRECO_ATUAL DECIMAL(10, 2) NOT NULL,
    CRIADO_EM TIMESTAMP,
    ATUALIZADO_EM TIMESTAMP,
    DELETADO_EM TIMESTAMP,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categorias(ID_CATEGORIA)
);

CREATE TABLE Pedidos (
    ID_PEDIDO INT AUTO_INCREMENT,
    ID_CLIENTE INT,
    DATA_PEDIDO TIMESTAMP,
    DATA_FINALIZADO TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL,
    ESTIMATIVA_PREPARO TIMESTAMP,
    PRIMARY KEY (ID_PEDIDO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE)
);

CREATE TABLE Pedido_Produto (
    ID_PEDIDO_PRODUTO INT AUTO_INCREMENT,
    ID_PEDIDO INT,
    ID_PRODUTO INT,
    QUANTIDADE INT,
    PRECO_VENDA DECIMAL(10, 2) NOT NULL,
    OBSERVACAO VARCHAR(200),
    PRIMARY KEY (ID_PEDIDO_PRODUTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES Pedidos(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES Produtos(ID_PRODUTO)
);