name: Deploy Actions
on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Executar testes unit치rios
        run: |
          export PAGAMENTO_SERVICE="${{ secrets.PAGAMENTO_SERVICE }}"
          mvn clean
          mvn test -P test

      - name: Generate JaCoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1

      - name: Log coverage percentage
        run:
          echo "coverage = ${{ steps.jacoco.ouputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/


#
#  build:
#    runs-on: ubuntu-latest
#    needs: system-test
#
#
#    steps:
#      - name: Checkout do c칩digo
#        uses: actions/checkout@v3
#
#      - name: Configurar o JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'adopt'
#          java-version: '17'
#          package: '*.jar'
#
#      - name: Build com Maven
#        run: |
#          export MYSQL_HOST="${{ secrets.MYSQL_HOST }}"
#          mvn package
#
#
#  publish:
#    runs-on: ubuntu-latest
#    needs: build
#
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout do c칩digo
#        uses: actions/checkout@v3
#
#      - name: Configurar o JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'adopt'
#          java-version: '17'
#          package: '*.jar'
#      - name: Publish package
#        run: |
#          export MYSQL_HOST="${{ secrets.MYSQL_HOST }}"
#          mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}