name: Deploy Actions
on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD  }}
          MYSQL_DATABASE: food_58
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Executar testes unit치rios
        run: |
          export PAGAMENTO_SERVICE="${{ secrets.PAGAMENTO_SERVICE }}"
          export MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}"
          export MYSQL_HOST="${{ secrets.MYSQL_HOST }}"
          export PEDIDOS_PRODUCAO="${{ secrets.PEDIDOS_PRODUCAO }}"
          export PEDIDOS_FINALIZADOS="${{ secrets.PEDIDOS_FINALIZADOS }}"
          export PEDIDOS_QUEUE="${{ secrets.PEDIDOS_QUEUE }}"
          export PAGAMENTOS_CONFIRMADOS_QUEUE="${{ secrets.PAGAMENTOS_CONFIRMADOS_QUEUE }}"
          export PAGAMENTOS_CANCELADOS_QUEUE="${{ secrets.PAGAMENTOS_CANCELADOS_QUEUE }}"
          export AWS_REGION="us-east-1"
          mvn clean
          mvn test -P test

      - name: Generate JaCoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1

      - name: Log coverage percentage
        run:
          echo "coverage = ${{ steps.jacoco.ouputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

  build:
    runs-on: ubuntu-latest
    needs: unit-test

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD  }}
          MYSQL_DATABASE: food_58
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          package: '*.jar'

      - name: Build com Maven
        run: |
          export MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}"
          export MYSQL_HOST="${{ secrets.MYSQL_HOST }}"
          export PEDIDOS_PRODUCAO="${{ secrets.PEDIDOS_PRODUCAO }}"
          export PEDIDOS_FINALIZADOS="${{ secrets.PEDIDOS_FINALIZADOS }}"
          export PEDIDOS_QUEUE="${{ secrets.PEDIDOS_QUEUE }}"
          export PAGAMENTOS_CONFIRMADOS_QUEUE="${{ secrets.PAGAMENTOS_CONFIRMADOS_QUEUE }}"
          export PAGAMENTOS_CANCELADOS_QUEUE="${{ secrets.PAGAMENTOS_CANCELADOS_QUEUE }}"
          export AWS_REGION="us-east-1"
          mvn package


  publish:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD  }}
          MYSQL_DATABASE: food_58
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3
      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          package: '*.jar'
      - name: Publish package
        run: |
          export MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}"
          export MYSQL_HOST="${{ secrets.MYSQL_HOST }}"
          export PEDIDOS_PRODUCAO="${{ secrets.PEDIDOS_PRODUCAO }}"
          export PEDIDOS_FINALIZADOS="${{ secrets.PEDIDOS_FINALIZADOS }}"
          export PEDIDOS_QUEUE="${{ secrets.PEDIDOS_QUEUE }}"
          export PAGAMENTOS_CONFIRMADOS_QUEUE="${{ secrets.PAGAMENTOS_CONFIRMADOS_QUEUE }}"
          export PAGAMENTOS_CANCELADOS_QUEUE="${{ secrets.PAGAMENTOS_CANCELADOS_QUEUE }}"
          export AWS_REGION="us-east-1"
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
